export const blogroll = [
  { 
    title: "swissmiss",
    url: "https://www.swiss-miss.com",
    description: "Tina Roth Eisenberg",
    category: "Design & Inspiration",
  },
  { 
    title: "Behance",
    url: "http://www.behance.net",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Co.Design",
    url: "https://www.fastcompany.com",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Design Milk",
    url: "https://design-milk.com/",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Fubiz™",
    url: "https://www.fubiz.net",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Beautiful Life",
    url: "https://www.beautifullife.info",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "kottke.org",
    url: "https://kottke.org/",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "LOW←TECH MAGAZINE",
    url: "https://solar.lowtechmagazine.com/posts/",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Unmatched Style",
    url: "https://unmatchedstyle.com",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Siteinspire",
    url: "https://www.siteinspire.com",
    description: "",
    category: "Design & Inspiration",
  },
  { 
    title: "Signal vs. Noise",
    url: "https://signalvnoise.com/svn3/",
    description: "",
    category: "Writing",
  },
  { 
    title: "zen habits",
    url: "https://zenhabits.net/",
    description: "",
    category: "Writing",
  },
  { 
    title: "Tomas Laurinavicius",
    url: "https://tomaslau.com/",
    description: "",
    category: "Writing",
  },
  { 
    title: "Still Drinking",
    url: "https://www.stilldrinking.org/",
    description: "",
    category: "Writing",
  },
  { 
    title: "Joel on Software",
    url: "https://www.joelonsoftware.com",
    description: "",
    category: "Writing",
  },
  { 
    title: "MOR10",
    url: "https://mor10.com/",
    description: "",
    category: "Writing",
  },
  { 
    title: "flaviocopes.com",
    url: "https://flaviocopes.com/",
    description: "",
    category: "Writing",
  },
  { 
    title: "Herman's blog",
    url: "https://herman.bearblog.dev/",
    description: "",
    category: "Writing",
  },
  { 
    title: "Smashing Magazine",
    url: "https://www.smashingmagazine.com/",
    description: "",
    category: "Magazines",
  },
  { 
    title: "Increment",
    url: "https://increment.com",
    description: "",
    category: "Magazines",
  },
  { 
    title: "UXmatters",
    url: "https://www.uxmatters.com/",
    description: "",
    category: "Magazines",
  },
  { 
    title: "24 ways",
    url: "https://24ways.org/",
    description: "",
    category: "Magazines",
  },
  { 
    title: "CSS-Tricks",
    url: "https://css-tricks.com",
    description: "",
    category: "Magazines",
  },
  { 
    title: "A List Apart",
    url: "https://alistapart.com",
    description: "",
    category: "Magazines",
  },
  { 
    title: "Jim Nielsen’s Blog",
    url: "https://blog.jim-nielsen.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Sara Soueidan — UI developer",
    url: "https://www.sarasoueidan.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "the jsomers.net blog",
    url: "https://jsomers.net/blog",
    description: "",
    category: "Development",
  },
  { 
    title: "from jason",
    url: "https://fromjason.xyz/",
    description: "",
    category: "Development",
  },
  { 
    title: "David Airey, graphic designer",
    url: "https://www.davidairey.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "cssplay.co.uk",
    url: "http://www.cssplay.co.uk/",
    description: "",
    category: "Development",
  },
  { 
    title: "Josh Comeau's blog",
    url: "https://www.joshwcomeau.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "Ben Frain",
    url: "https://benfrain.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Snook.ca",
    url: "https://snook.ca/",
    description: "",
    category: "Development",
  },
  { 
    title: "Justin Tadlock",
    url: "https://justintadlock.com",
    description: "",
    category: "Development",
  },
  { 
    title: "overreacted — A blog by Dan Abramov",
    url: "https://overreacted.io/",
    description: "",
    category: "Development",
  },
  { 
    title: "remy sharp's b:log",
    url: "https://remysharp.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Bruce Lawson's personal site",
    url: "https://brucelawson.co.uk",
    description: "",
    category: "Development",
  },
  { 
    title: "Marc Grabanski",
    url: "http://marcgrabanski.com",
    description: "Creator of Frontend Masters",
    category: "Development",
  },
  { 
    title: "Bram.us",
    url: "https://www.bram.us",
    description: "",
    category: "Development",
  },
  { 
    title: "Jason Santa Maria | Articles", 
    url: "https://jasonsantamaria.com",
    description: "", 
    category: "Development",
  },
  { 
    title: "Trent Walton",
    url: "http://trentwalton.com",
    description: "",
    category: "Development",
  },
  { 
    title: "The Hickensian",
    url: "https://hicksdesign.co.uk/journal/",
    description: "",
    category: "Development",
  },
  { 
    title: "Adam Argyle", 
    url: "https://nerdy.dev",
    description: "Magician of CSS", 
    category: "Development",
  },
  { 
    title: "Ethan Marcotte",
    url: "https://ethanmarcotte.com",
    description: "",
    category: "Development",
  },
  { 
    title: "David Bushell",
    url: "https://dbushell.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Adactio",
    url: "https://adactio.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "Bradley Taunt",
    url: "https://tdarb.org//",
    description: "",
    category: "Development",
  },
  { 
    title: "Thoughts From Eric",
    url: "https://meyerweb.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "Stéphanie Walter",
    url: "https://stephaniewalter.design/",
    description: "",
    category: "Development",
  },
  { 
    title: "Den Odell",
    url: "https://denodell.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Max Böck",
    url: "https://mxb.dev",
    description: "",
    category: "Development",
  },
  { 
    title: "simurai",
    url: "http://simurai.com",
    description: "",
    category: "Development",
  },
  { 
    title: "bitsofcode",
    url: "https://bitsofco.de/",
    description: "",
    category: "Development",
  },
  { 
    title: "Ratfactor Feed",
    url: "http://ratfactor.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "Lusitos Tech Blog",
    url: "https://blog.lusito.info",
    description: "",
    category: "Development",
  },
  { 
    title: "macwright.com",
    url: "https://macwright.com",
    description: "", 
    category: "Development",
  },
  { 
    title: "Matthias Ott",
    url: "https://matthiasott.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Blog – azumbrunnen", 
    url: "https://azumbrunnen.me",
    description: "", 
    category: "Development",
  },
  { 
    title: "Functioning Form: Interface Design",
    url: "http://www.lukew.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Keith J. Grant",
    url: "https://keithjgrant.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "Brad Frost",
    url: "https://bradfrost.com",
    description: "",
    category: "Development",
  },
  { 
    title: "Harry Roberts",
    url: "https://csswizardry.com/",
    description: "aka CSS Wizardry",
    category: "Development",
  },
  { 
    title: "Ahmad Shadeed",
    url: "https://ishadeed.com/",
    description: "",
    category: "Development",
  },
  { 
    title: "daverupert.com",
    url: "https://daverupert.com",
    description: "",
    category: "Development",  
  },
  { 
    title: "Jeffrey Zeldman Presents",
    url: "https://zeldman.com/",
    description: "The dude that started web standards revolution",
    category: "Development",
  },
  { 
    title: "On my Om",
    url: "https://om.co",
    description: "",
    category: "News",
  },
  { 
    title: "TechCrunch",
    url: "https://techcrunch.com/",
    description: "",
    category: "News",
  },
  { 
    title: "The Next Web",
    url: "https://thenextweb.com",
    description: "",
    category: "News",
  },
  { 
    title: "Daring Fireball",
    url: "https://daringfireball.net/",
    description: "",
    category: "News",
  },
];

export const getBlogsByCategory = (category: string) => {
  return blogroll.filter((blog) => blog.category === category).map((blog) => ({
    title: blog.title,
    description: blog.description,
    url: blog.url,
  }));
};